import { CreateExamMarkDTO } from "../../dto/Exam/CreateExamMarkDTO";
import { IExamMarkRepository } from "../../../domain/repositories/Exam/IExamMarkRepoInterface";
import { IExamRepository } from "../../../domain/repositories/Exam/IExamRepoInterface";
import { StudentDetails } from "../../../domain/repositories/Admin/IStudnetRepository";
import { ExamMarkEntity } from "../../../domain/entities/Exam/ExamMarkEntity";

export class ExamMarkCreateUseCase {
  constructor(
    private examMarkRepo: IExamMarkRepository,
    private studentRepo: StudentDetails,
    private examRepo: IExamRepository
  ) { }

  async execute(teacherId: string, data: CreateExamMarkDTO) {

    const exam = await this.examRepo.findById(data.examId);
    if (!exam) {
      throw new Error("Exam not found");
    }

    if (exam.teacherId.toString() !== teacherId) {
      throw new Error("You are not allowed to evaluate this exam");
    }


    const student = await this.studentRepo.findStudentById(data.studentId);
    if (!student) {
      throw new Error(`Student not found: ${data.studentId}`);
    }


    if (student.classId.toString() !== exam.classId.toString()) {
      throw new Error("Student does not belong to this exam class");
    }


    const existing = await this.examMarkRepo.findByExamAndStudent(
      data.examId,
      data.studentId
    );

    if (existing) {
      throw new Error("Marks already assigned for this student");
    }


    const markEntity = new ExamMarkEntity(
      "", // ID will be generated by DB
      data.examId,
      data.studentId,
      teacherId,
      data.marksObtained,
      ExamMarkEntity.calculateProgress(data.marksObtained),
      data.remarks || "",
      null,
      null,
      null,
      new Date(),
      new Date()
    );

    return await this.examMarkRepo.create(markEntity);
  }
}
