import { IExamCreateRepository } from "../../../domain/UseCaseInterface/Exam/IExamCreateUseCase";
import { CreateExamDTO } from "../../dto/Exam/CreateExamDTO";
import { ExamEntity } from "../../../domain/entities/Exam/ExamEntity";
import { IExamRepository } from "../../../domain/repositories/Exam/IExamRepoInterface";
import { IClassRepository } from "../../../domain/repositories/Classrepo/IClassRepository";
import { ITeacherCreate } from "../../../domain/repositories/TeacherCreate";
import { ExamErrorMessages } from "../../../shared/constants/ExamErrorMessages";

export class ExamCreateUseCase implements IExamCreateRepository {
  constructor(
    private examRepo: IExamRepository,
    private classRepo: IClassRepository,
    private teacherRepo: ITeacherCreate
  ) { }

  async execute(data: CreateExamDTO): Promise<ExamEntity> {
    ExamEntity.validateDate(data.examDate);

    const classData = await this.classRepo.findById(data.classId);
    if (!classData) {
      throw new Error(ExamErrorMessages.CLASS_NOT_FOUND);
    }

    const teacher = await this.teacherRepo.findById(data.teacherId);
    if (!teacher) {
      throw new Error(ExamErrorMessages.TEACHER_NOT_FOUND);
    }

    const subjectExists = teacher.subjects;

    if (!subjectExists) {
      throw new Error(ExamErrorMessages.TEACHER_NOT_ASSIGNED_TO_SUBJECT);
    }

    const examEntity = new ExamEntity(
      "", // ID will be generated by DB
      data.examId ?? "",
      data.title,
      data.type,
      data.classId,
      classData.className,
      classData.division,
      data.subject,
      data.teacherId,
      teacher.name,
      data.examDate,
      data.startTime,
      data.endTime,
      data.maxMarks,
      data.passMarks,
      data.description || "",
      "DRAFT"
    );

    return await this.examRepo.createExam(examEntity);

  }
}
