import { IAIService } from "../../../domain/repositories/AI/IAIService";
import { IYouTubeService, IYouTubeVideo } from "../../../domain/repositories/AI/IYouTubeService";
import { IAISessionRepository } from "../../../domain/repositories/AI/IAISessionRepository";
import { AISession, AIChatMessage } from "../../../domain/entities/AISession";
import { v4 as uuidv4 } from 'uuid';

const bannedWords = [
    "sex", "porn", "nude", "xxx",
    "violence", "kill",
    "drug", "weed",
    "suicide", "self harm"
];

function isUnsafeQuestion(question: string): boolean {
    const q = question.toLowerCase();
    return bannedWords.some(word => q.includes(word));
}

interface AIResponse {
    answer: string;
    videos: IYouTubeVideo[];
    sessionId: string;
}

export class AskAIDoubtUseCase {
    constructor(
        private aiService: IAIService,
        private youtubeService: IYouTubeService,
        private sessionRepository: IAISessionRepository
    ) { }

    async execute(studentId: string, question: string, sessionId?: string): Promise<AIResponse> {
        if (!question) {
            throw new Error("Question is required");
        }

        if (isUnsafeQuestion(question)) {
            throw new Error("This content is not allowed.");
        }

        console.log(`AskAIDoubtUseCase: Processing question: "${question}"`);

        // First get the answer and corrected question from AI
        try {
            const aiResult = await this.aiService.getAnswer(question);
            const { correctedQuestion, answer } = aiResult;

            console.log(`AskAIDoubtUseCase: Question "${question}" corrected to "${correctedQuestion}"`);

            // Then search videos using the corrected question for better results
            const videos = await this.youtubeService.searchVideos(correctedQuestion);

            console.log("AskAIDoubtUseCase: Completed. Videos found:", videos.length);

            // --- Persistence Logic ---
            let currentSessionId = sessionId;

            // Create User Message
            const userMessage: AIChatMessage = {
                id: uuidv4(),
                role: 'user',
                content: question,
                timestamp: new Date()
            };

            // Create AI Message
            const aiMessage: AIChatMessage = {
                id: uuidv4(),
                role: 'ai',
                content: answer,
                videos: videos, // Store videos with the message
                timestamp: new Date()
            };

            if (currentSessionId) {
                // Update existing session
                const session = await this.sessionRepository.findById(currentSessionId);
                if (session) {
                    await this.sessionRepository.addMessage(currentSessionId, userMessage);
                    await this.sessionRepository.addMessage(currentSessionId, aiMessage);
                } else {
                    // Session ID provided but not found, treat as new session? Or error?
                    // Let's create a new one to be safe/resilient
                    console.warn(`Session ${currentSessionId} not found, creating new.`);
                    currentSessionId = undefined; // Trigger creation logic below
                }
            }

            if (!currentSessionId) {
                // Create new session
                const newSession = new AISession(
                    "", // ID generated by DB/Repo
                    studentId,
                    question.substring(0, 50) + (question.length > 50 ? "..." : ""), // Title from first question
                    [userMessage, aiMessage],
                    new Date(),
                    new Date()
                );
                const createdSession = await this.sessionRepository.create(newSession);
                currentSessionId = createdSession.id;
            }

            return { answer, videos, sessionId: currentSessionId };

        } catch (error) {
            console.error("AskAIDoubtUseCase: Error during execution", error);
            throw error;
        }
    }
}
