name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
#do some change
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/School_Management
            git reset --hard
            git pull origin main

            # 🔹 Backend
            cd backend
            npm install
            # Use npx to ensure pm2 is found even if not in PATH
            npx pm2 restart backend || npx pm2 start server.js --name backend

            # 🔹 Frontend
            cd ../Frontend/school
            npm install
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            # Ensure target directory exists and copy files
            sudo mkdir -p /var/www/html/
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            # 🔹 Nginx Config
            sudo cp ~/School_Management/nginx.conf /etc/nginx/sites-available/default
            sudo systemctl restart nginx

            # 🔹 Restart Backend
            cd ~/School_Management/backend
            npx pm2 restart backend || npx pm2 start dist/server.js --name backend
